# Changes here will be overwritten by Copier
_commit: v0.2.5
_src_path: gh:ninanor/template-python
author_name: Niccolò Cantù
debug: false
default_branch_name: main
docker: false
email: niccolo.cantu@nina.no
notebook: false
project_name: PGDedump
project_slug: pg_dedump
repo_name: pg_dedump
repo_org: ninanor
template_type: python
type_annotations: false
